# Generated by Django 4.1.4 on 2022-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemLocation',
            new_name='itemLocation',
        ),
    ]
